ny_taxi_dbt:
  outputs:
    dev:
      dataset: dbt_olegagapov
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/app/dbt/google.json
      location: europe-west6
      method: service-account
      priority: interactive
      project: booming-landing-375221
      threads: 1
      type: bigquery
  target: dev
